export const types = {
  MOSTRAR_ALERTA: "[AUTH] mostrar alerta",
  OCULTAR_ALERTA: "[AUTH] ocultar alerta",
  LOGIN_ERROR: "[AUTH] login error",
  LOGIN_EXITOSO: "[AUTH] login existoso",
  REGISTRO_EXITOSO: "[AUTH] registro exitoso",
  REGISTRO_ERROR: "[AUTH registro error]",
  OBTENER_USUARIO: "[AUTH] obtener usuario",
  CERRAR_SESION: "[AUTH] cerrar sesion",
  INICIAR_SESION: "[AUTH] inicia sesion",
  USER_CHANGEPHOTO: "[AUTH] USER_CHANGEPHOTO",
  RESET_PASSWORD: "[AUTH] RESET_PASSWORD",
};

export const SHOW_ERRORS_API = "SHOW_ERRORS_API";

export const GET_ALL_TOURS = "GET_ALL_TOURS";
export const STORE_TOURS = "STORE_TOURS";
export const DELETE_TOUR = "DELETE_TOUR";
export const TOTAL_VENTAS_DIA = "TOTAL_VENTAS_DIA";
export const TOTAL_VENTAS_SEMANA = "TOTAL_VENTAS_SEMANA";
export const TOTAL_VENTAS_MES = "TOTAL_VENTAS_MES";

//categorias
export const GET_ALL_CATEGORIES_UNITS = "GET_ALL_CATEGORIES_UNITS";
export const CREATE_CATEGORIES_UNITS = "CREATE_CATEGORIES_UNITS";
export const UPDATE_CATEGORIES_UNITS = "UPDATE_CATEGORIES_UNITS";
export const DELETE_CATEGORIES_UNITS = "DELETE_CATEGORIES_UNITS";
//unidades
export const GET_ALL_UNITS = "GET_ALL_UNITS";
export const CREATE_UNIT = "CREATE_UNIT";
export const UPDATE_UNIT = "UPDATE_UNIT";
export const DELETE_UNIT = "DELETE_UNIT";

//cotizaciones
export const GET_QOUTATION_PENDING = "GET_QOUTATION_PENDING";
export const GET_QUOTATION_ACCEPTED = "GET_QUOTATION_ACCEPTED";
export const GET_QUOTATION_BY_ID = "GET_QUOTATION_BY_ID";
export const UPDATE_QUOTATION_STATUS = "UPDATE_QUOTATION_STATUS";
export const PROMOTE_TO_CUSTOMER = "PROMOTE_TO_CUSTOMER";
export const CONVERT_TO_ORDER = "CONVERT_TO_ORDER";
